### ISSUE TITLE
Lack of Convert Chaining

### ISSUE THREAD

**Issue by caasion** [aptend/typing-transformer-obsidian#31]
Hello,

I'm loving the plugin so far, but it would be great if the plugin can preform multiple converts in the order of the converts.

I have the following converting rules:
```
# auto pair and convert
'<|' -> '<|>' 
'(<|>)' -> '⟨|⟩' 
'((<|>))' -> '⟪|⟫' 
'---\n\n|' -> '---\n|\n---' 

# Selection Insert Rules
'<'  -> '<' + '>'

# Brackets
'((<|' -> '⟪|'
'>|))' -> '⟫|'
'(<|' -> '⟨|'
'>|)' -> '⟩|'
'[(<|' -> '⦗|'
'>|)]' -> '⦘|'
'[⟨|' -> '⦗|'
'⟩]|' -> '⦘|'
```
However, when I press the keys `(` `<`, 
it results in `(<|>)` _(`|` represents the cursor)_ 
which is not ideal since I have other rules ([`'(<|' -> '⟨|'`] & [`'(<|>)' -> '⟨|⟩'`]) 
that should convert these into angled brackets.

I'm not sure how to optimize it on the performance side, but if you could still continue to loop through the list after something is converted, that would make the plugin even more versatile.
For example, when I press the keys `(` `<`:

1. [`'<|' -> '<|>'`] will trigger along with the default bracket auto pair, turning it into `(<|>)`
2. Then, the plugin will loop through all the rules after the one that has triggered, so anything after `'<|' -> '<|>'`
3. [`'(<|>)' -> '⟨|⟩' `], which happens to match, will further convert the text into `'⟨|⟩'`

Please consider adding this feature as it will make the plugin a lot more powerful.

**Comment by caasion** [comment]
I am not sure if this is related, but if you use characters (only tested `*` and `_`) that Obsidian auto pairs by default, the conversion doesn't work.
These are the relevant rules:
```
'<|' -> '<|>'
'<_|>' -> '<small>|</small>' 
'<_|_>' -> '<small>|</small>' 
'<*|>' -> '<small>|</small>' 
'<*|*>' -> '<small>|</small>' 
```
When I press `<` + `_` or `<` + `*`, none of the rules except for the first one triggers.

**Comment by aptend** [comment]
> I am not sure if this is related, but if you use characters (only tested `*` and `_`) that Obsidian auto pairs by default, the conversion doesn't work. These are the relevant rules:

Indeed, `*` and `_` will trigger the default auto pair rules of Obsidian, and its priority is so high that the plugin can't change. When you type `_`， for the plugin, the input will be `__` instead of `_`， which can't be recognized.

I guess there are two solutions.
1. Disable the default auto pair in Obsidian Editor settings and let the plugin take control
![image](https://user-images.githubusercontent.com/49832303/183092341-d149d661-7111-41bb-b4cc-f646de9d390b.png)

3. Use special trigger char to bypass, for example
```py
'<s-|>' -> '<small>|</small>' 
'<|' -> '<|>'
```

---

Convert chain is an appealing idea, but how to implement it might not be trivial, I will think about it anyway.

For now, for your cases, I would probably disable the default auto pair in Obsidian and write rules like this:

```py
'((<|))' -> '⟪|'
'⟪>|' -> '⟪|⟫'

'(<|)' -> '⟨|'
'⟨>|' -> '⟨|⟩'

'([|)' -> '⦗|'
'⦗]|' -> '⦗|⦘'

# disable auto pair brackets and let the plugin take over
'(|' -> '(|)'
'[|' -> '[|]'
```

the process to write  '⟪|⟫':
1. type two `(`, the rule `'(|' -> '(|)'` will turn it into `((|))`
2. type `<`, the rule `'((<|))' -> '⟪|'` will turn it into  '⟪|'
3. type `>`, the rule `'⟪>|' -> '⟪|⟫'` will turn it into `'⟪|⟫`

That is what you are looking for?
